version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: ls-91f7a673d9d0c45456f9f657d044ba93b46006a6.c54qm2cy0j1x.us-east-1.rds.amazonaws.com
      DB_NAME: global_db
      DB_USER: dbmasteruser
      DB_PASSWORD: iir&ncoAQ4jkS+LNs_qRw7L}d&84QIT5
    volumes:
      - .:/var/www/html
